config/routes.rb
Tellmewhen::Application.routes.draw do
  
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  require File.expand_path("../../lib/logged_in_constraint", __FILE__)  

  # resources :races
  resources :events
  resources :event_dates
  resources :answers
  resources :questions
  resources :users
  resources :event_names

  resources :user_questions
  delete "user_question_delete/:id" => 'UserQuestions#destroy', :as => :user_question_delete
  
  post "sessions/create"
  delete "sessions/destroy", :as => :logout
  get "sessions/new", :as => :login

  get "users/join" => "users#join", :as => :join

  # root :to => "users#show", :constraints => LoggedInConstraint.new(true)
  root :to => "pages#index"

  get "pages/about", :as => :about
  get "pages/contactus", :as => :contactus
  get "pages/terms", :as => :terms
  get "pages/privacy", :as => :privacy
  get "pages/index"
  get "pages/thank_you"
  
  get '/auth/failure' do
    p "oho"
    flash[:notice] = params[:message] # if using sinatra-flash or rack-flash
    # redirect '/'
  end
    
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  
  belongs_to :question
  belongs_to :event
  has_many :event_dates, through: :event
  
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  
  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  after_save :create_question
  
  has_many :answers
  has_many :questions, through: :answers
  has_many :event_dates
  
  accepts_nested_attributes_for :event_dates  
  
  def create_question
    question = Question.create(name: self.name)
    answer = Answer.new
    answer.question = question
    answer.event = self
    answer.save
  end
  
end

app/models/event_date.rb
class EventDate < ActiveRecord::Base
  
  belongs_to :event
  
  def days_left
    days_left = (date.to_datetime - DateTime.now).to_i
  end
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  
  has_many :user_questions
  has_many :users, :through => :user_questions
  has_many :answers

end

app/models/race.rb
# class Race < ActiveRecord::Base
#   
#   has_many :user_races
#   has_many :users, :through => :user_races
#   
# end

app/models/user.rb
class User < ActiveRecord::Base

  include ActiveModel::Validations

  # has_secure_password
  has_many :authorizations
  # has_many :user_races
  # has_many :races, :through => :user_races
  has_many :user_questions
  has_many :questions, :through => :user_questions
  
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_uniqueness_of :email
  validates_presence_of :email
  
  # custom validator 
  validates_with RegisteredValidator, :on => :update
  
  def self.create_from_hash!(hash)
    create(:name => hash['info']['name'])
  end

end

app/models/user_question.rb
class UserQuestion < ActiveRecord::Base

  belongs_to :user
  belongs_to :question
  has_many :answers, through: :question
  
end

app/models/user_race.rb
# class UserRace < ActiveRecord::Base
# 
#   belongs_to :user
#   belongs_to :race
#   
# end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find_by_id(params[:id])
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.create(params[:event])
    redirect_to new_event_date_url(:event => @event)
  end

  def edit
    @event = Event.find_by_id(params[:id])
  end
  
  def update
    Event.find_by_id(params[:id]).update_attributes(params[:event])
    redirect_to events_url
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
  
  def index
    if logged_in?
      redirect_to user_url(current_user)
    end
  end

  def contactus
  end
  
  def terms
  end
  
  def privacy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    render :text => request.env['omniauth.auth'].inspect

    # auth = request.env['omniauth.auth']
    # unless @auth = Authorization.find_from_hash(auth)
      # Create a new user or add an auth to existing user, depending on
      # whether there is already a user signed in.
      # @auth = Authorization.create_from_hash(auth, current_user)
    # end
    # Log the authorizing user in.
    # self.current_user = @auth.user
    # redirect_to :root

    # if current_user
    #   @user = current_user
    #   before_cnt = @user.authentications.count
    #   Authenticator.add_authentication_to_user @user, params[:provider], auth_hash
    #   flash[:notice] = "Successfully authentication"
    # else
    #   @user = Authenticator.find_or_create_user_from_auth_hash params[:provider], auth_hash
    #   cookies.permanent.signed[:remember_token] = @user.id
    #   flash[:notice] = "Signed in"
    # end

    # render :text => "Welcome, #{current_user.name}."
    # user = User.find_by_email(params[:email])
    # if user && user.authenticate(params[:password])
    #   cookies.permanent.signed[:user_id] = user.id
    #   flash[:notice] = "Thanks for signing in!"
    #   redirect_to user_path(current_user)
    # else
    #   flash[:notice] = "Whoa, try again"
    #   render :new
    # end
  end
  
  def destroy
    reset_session
    cookies[:user_id] = {:expires => 1.day.ago.utc}
    redirect_to :root, :notice => "You are logged out."
  end
  
  # def auth_hash
  #     request.env['omniauth.auth']
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :require_user, :except => [:new, :create]

  def show
    @user = current_user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  def edit

  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        UserMailer.new_user_email(@user).deliver
        sign_in_user(@user)
        format.html { redirect_to :root, :notice => 'Thanks for signing up!' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  # def join
  #   @user = User.where(:email => params[:e], :email_token => params[:m]).first
  #   puts @user.inspect
  #   redirect_to new_user_registration_url and return if @user.nil?
  #   sign_in @user
  #   redirect_to edit_user_registration_url(:l => params[:l])
  # end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/event_dates_helper.rb
module EventDatesHelper
end

app/helpers/event_names_helper.rb
module EventNamesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/edit.html.erb
<h1>Answers#edit</h1>
<p>Find me in app/views/answers/edit.html.erb</p>

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit "<%= @event.name %>"</h1>
<%= form_for @event do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br />
  
  <!-- <#%= form.fields_for :event_dates do |event_date| %>
    
    <#%= event_date.text_field :name %>
    <br />
    <#%= event_date.date_select :date %>
    <br />
  <#% end %>
  <br /> -->
  <%= form.submit %>
<% end %>

app/views/events/index.html.erb
<h1>Events!</h1>
<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event.name, event_url(event) %> - 
      <%= link_to "Join", user_questions_url(event: event), method: :post %> - 
      <%= link_to "Edit", edit_event_url(event) %>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>Create A New Event!</h1>
<%= form_for @event do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br />
  
  <!-- <#%= form.fields_for :event_dates do |event_date| %>
    
    <#%= event_date.text_field :name %>
    <br />
    <#%= event_date.date_select :date %>
    <br />
  <#% end %>
  <br /> -->
  <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<ul>
  <% @event.event_dates.each do |event_date| %>
    <li>
      <%= event_date.name %>: <%= event_date.date.strftime("%B %d, %Y") %> <%= link_to "Edit", edit_event_date_url(event_date) %>
    </li>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div>
	<div class="clearfix"> 
		<%= f.label :first_name %>
		<div class="input">
			<%= f.text_field :first_name, :class => "name" %>
		</div>
	</div>
	<div class="clearfix">
		<%= f.label :last_name %>
		<div class="input">
			<%= f.text_field :last_name %>
		</div>
	</div>
	<div class="clearfix">
		<%= f.label :email %>
		<div class="input">
			<%= f.text_field :email %>
		</div>
	</div>
	<% if @user.registered == false %>
	<div>
		<div>
			<p>Choose a password:</p>
		</div>
	</div>
	<% end %>
	<div class="clearfix">
		<%= f.label :password %>
		<div class="input">
			<%= f.password_field :password %>
		</div>
	</div>
	<div class="clearfix">
		<%= f.label :password_confirmation, 'Confirm password'%>
		<div class="input">
			<%= f.password_field :password_confirmation %>
		</div>
	</div>
	<%= f.submit :class => "button" %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="steps">
	<% if @user.registered == false %>
		Thank you, we will send you an email when we find out about the registration date for the <%= params[:betold] %> race. An email has been sent to <%= params[:email] %> to complete the registration.
	<% else %>
		Edit your profile. Leave password and/or email blank if you wish to keep the same password.
	<% end %>
</div>
<div class="question">
	<% if @user.registered == false %>
		<h2>Complete your profile:</h2>
	<% else %>
		<h2>Edit your profile:</h2>
	<% end %>
	<%= render 'form' %>
</div>

app/views/users/edit_password.html.erb
<%= form_for(@user), :url => { :action => "edit" } do |f| %>
	<div class="steps">
		Edit your password.
	</div>
	<div class="question">
		<div class="clearfix">
			<%= f.label :password %>
			<div class="input">
				<%= f.password_field :password %>
			</div>
		</div>
		<div class="clearfix">
			<%= f.label :password_confirmation, 'Confirm password'%>
			<div class="input">
				<%= f.password_field :password_confirmation %>
			</div>
		</div>
		<%= f.submit :class => "button" %>
	</div>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Register with uTellmewhen:</h1>

<%= render 'form' %>
	
<div class="login">
	<h3>or <%= link_to "sign in", login_url %></h3>
</div>

app/views/users/show.html.erb
<div>
  <h2>Add a new event:</h2>
	<%= render 'questions/search' %>
</div>
<hr />
<div>
  <% if @user.questions.count > 0 %>
		<div>
			<h2>Your events:</h2>
			<ul>
				<% @user.user_questions.each do |uq| %>
				<li id="<%= dom_id(uq) %>">
				  <%= uq.question.name %> (created <%= time_ago_in_words(uq.created_at.to_time) %> ago) <%= link_to "Delete", user_question_delete_url(uq.id), :method => :delete %>
				</li>
				  <ul>
				    <% uq.answers.each do |a| %>
				      <li>
				        => <%= a.event.name %>
				        <ul>
				          <% a.event_dates.each do |ed| %>
                    <li>
                      <%= ed.name %>: <%= ed.date.strftime("%B %d, %Y") %> (<%= ed.days_left %> days left)
                    </li>
				          <% end %>
				        </ul><br />
				      </li>
				    <% end %>
				  </ul>
				  <hr />
				<% end %>
			</ul>
		</div>
	<% else %>
		Your events will show here. You are not watching any events at this time.
	<% end %>
</div>