config/routes.rb
Tellmewhen::Application.routes.draw do
  
  match '/auth/:provider/callback', :to => 'sessions#create'
  
  require File.expand_path("../../lib/logged_in_constraint", __FILE__)  

  # resources :races
  resources :events
  resources :event_dates
  resources :answers
  resources :questions
  resources :users
  resources :event_names

  resources :user_questions
  delete "user_question_delete/:id" => 'UserQuestions#destroy', :as => :user_question_delete
  
  post "sessions/create"
  delete "sessions/destroy", :as => :logout
  get "sessions/new", :as => :login

  get "users/join" => "users#join", :as => :join

  # root :to => "users#show", :constraints => LoggedInConstraint.new(true)
  root :to => "pages#index"

  get "pages/about", :as => :about
  get "pages/contactus", :as => :contactus
  get "pages/terms", :as => :terms
  get "pages/privacy", :as => :privacy
  get "pages/index"
  get "pages/thank_you"
  
  get '/auth/failure' do
    p "oho"
    flash[:notice] = params[:message] # if using sinatra-flash or rack-flash
    # redirect '/'
  end
    
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  
  belongs_to :question
  belongs_to :event
  has_many :event_dates, through: :event
  
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  
  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end
  
end

app/models/event.rb
class Event < ActiveRecord::Base
  
  after_save :create_question
  
  has_many :answers
  has_many :questions, through: :answers
  has_many :event_dates
  
  accepts_nested_attributes_for :event_dates  
  
  def create_question
    question = Question.create(name: self.name)
    answer = Answer.new
    answer.question = question
    answer.event = self
    answer.save
  end
  
end

app/models/event_date.rb
class EventDate < ActiveRecord::Base
  
  belongs_to :event
  
  def days_left
    days_left = (date.to_datetime - DateTime.now).to_i
  end
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  
  has_many :user_questions
  has_many :users, :through => :user_questions
  has_many :answers

end

app/models/race.rb
# class Race < ActiveRecord::Base
#   
#   has_many :user_races
#   has_many :users, :through => :user_races
#   
# end

app/models/user.rb
class User < ActiveRecord::Base

  include ActiveModel::Validations

  # has_secure_password
  has_many :authorizations
  # has_many :user_races
  # has_many :races, :through => :user_races
  has_many :user_questions
  has_many :questions, :through => :user_questions
  
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates_uniqueness_of :email
  validates_presence_of :email
  
  # custom validator 
  validates_with RegisteredValidator, :on => :update
  
  def self.create_from_hash!(hash)
    create(:name => hash['info']['name'])
  end

end

app/models/user_question.rb
class UserQuestion < ActiveRecord::Base

  belongs_to :user
  belongs_to :question
  has_many :answers, through: :question
  
end

app/models/user_race.rb
# class UserRace < ActiveRecord::Base
# 
#   belongs_to :user
#   belongs_to :race
#   
# end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
  
  def index
    if logged_in?
      redirect_to user_url(current_user)
    end
  end

  def contactus
  end
  
  def terms
  end
  
  def privacy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :require_user, :except => [:new, :create]

  def show
    @user = current_user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  def edit

  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        UserMailer.new_user_email(@user).deliver
        sign_in_user(@user)
        format.html { redirect_to :root, :notice => 'Thanks for signing up!' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

  # def join
  #   @user = User.where(:email => params[:e], :email_token => params[:m]).first
  #   puts @user.inspect
  #   redirect_to new_user_registration_url and return if @user.nil?
  #   sign_in @user
  #   redirect_to edit_user_registration_url(:l => params[:l])
  # end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/event_dates_helper.rb
module EventDatesHelper
end

app/helpers/event_names_helper.rb
module EventNamesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>uTellmewhen</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta content='width=device-width, minimum-scale=1.0, maximum-scale=1.0' name='viewport'>
</head>
<body id="<%= controller.action_name %>">
	<div class="wrap">
		<header>
			<nav>
				<div class="logo">
					<%= link_to "Home", root_url %>
				</div>
				<% if logged_in? %>
					<div class="welcome">
					  <%= link_to("Hi #{current_user.first_name}!", user_url(current_user)) if current_user.first_name %> (<%= link_to "edit profile", edit_user_path(current_user) %> - <%= link_to "sign out", logout_path, :method => :delete %>)
					</div>
				<% else %>
					<div class="welcome">Never miss a race registration again.</div>
				<% end %>
			</nav>
		</header>
		<div class="main clearfix">
			<%= yield %>
		</div>
	</div>
	<footer>
		<div style="float:left;margin-top:7px">
			<%#= link_to "Blog", "http://utellmewhen.wordpress.com" %>
			<%#= link_to "About", about_url %>
			<%#= link_to "Contact", contactus_url %>
			<%#= link_to "Privacy", privacy_url %>
			<%#= link_to "Terms", terms_url %>
     		<%= link_to "Questions", questions_url %>
			<%= link_to "Events", events_url %>
			<% if not logged_in?  %>
			  -
			  <%= link_to "Sign in", login_url %>
			<% else %>
			  -
			  <%= link_to "Sign out", logout_path, :method => :delete %>
			<% end %>
		</div>
		<div style="float:right"><%= link_to image_tag("twitter.png", :alt => "@utellmewhen"), "http://www.twitter.com/utellmewhen" %>
			<%= link_to image_tag("builtinchicago_logo_badge.png", :alt => "Built in Chicago"), "http://www.builtinchicago.org" %>
		</div>
	</footer>
  	<%#= render "shared/getsatisfaction" %>
  	<%#= render "shared/googleanalytics" %>
</body>
</html>

app/views/layouts/user_mailer.html.erb
<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff">
	<tbody>
		<tr>
			<td>
				<table width="600" border="0" cellspacing="0" cellpadding="0" align="center" style="margin-left:auto;margin-right:auto;padding:0;border-left:15px solid #fff;border-right:15px solid #fff">
					<tbody>
						<tr>
							<td width="175">
								<a href="http://utellmewhen.com" style="border:0px;display:block;min-height:58px" target="_blank"> <img src="http://utellmewhen.com/assets/utmw_logo3.png" alt="uTellmewhen"></a>
							</td>
							<td align="right" style="text-align:right;font-family:'Lucida Sans Unicode','Lucida Grande',sans-serif;font-size:11px;font-weight:300;color:#132946"><h3 style="text-decoration:none;font-size:13px;line-height:18px;margin:0;padding:0;font-weight:100;font-family:'Trebuchet MS',Arial,Helvetica,sans-serif;color:#132946"><a href="mailto:hello@utellmewhen.com" style="text-decoration:none;color:#94aed4;font-style:italic" target="_blank">hi@utellmewhen.com</a> • </h3>
	or reply to this email
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td>
				<table width="598" border="0" cellspacing="0" cellpadding="0" align="center" style="margin-left:auto;margin-right:auto;margin-top:30px">
					<tbody>
						<tr>
							<td>
								<h1 style="margin-left:20px;width:598px;font-family:Georgia,'Times New Roman',Times,serif;font-size:26px;line-height:40px;font-weight:300;color:#132946;margin-bottom:20px;margin-top:0">Dear Runner!</h1><p style="margin:0 0 15px 20px;padding:0 50px 0 0;width:548px;font-family:'Trebuchet MS',Arial,Helvetica,sans-serif;font-size:14px;line-height:30px;font-weight:300;color:#132946"><%= yield %></p>
									<p style="margin:0 0 30px 20px;padding:0;width:515px;font-family:'Trebuchet MS',Arial,Helvetica,sans-serif;font-size:14px;line-height:22px;font-weight:300;color:#132946">Best,<br><br>Jean Bahnik<br>Co-Founder and CEO</p>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td>
			</td>
		</tr>
		<tr>
			<td style="min-height:30px" align="center"><img src="http://utellmewhen.com/assets/utmw_line_598.png" alt="uTellmewhen"></td>
		</tr>
	</tbody>
</table>

app/views/pages/_old_login_links.html.erb
<div class="login">
<h3>
<% if logged_in? %>
       Hello, <%= current_user.first_name %>!
       <%= link_to "My Profile", user_url(current_user) %> | <%= link_to "Log Out", logout_path, :method => :delete %>
   <% else %>
     	<%= link_to "Sign In!", login_url %> | <%= link_to "Create an Account", new_user_url %>
     <% end %>
</h3>
</div>

app/views/pages/about.html.erb
<div class="pages">
About us:

We built uTellmewhen during startup weekend.
Our goal is to help people remember events and never miss them.

Team:

Jean Bahnik
</div>

app/views/pages/contactus.html.erb
<div class="pages">
Contact us:

In Chicago.
</div>

app/views/pages/index.html.erb
<div class="steps">
	<div class="num">
		<div class="count">
		1
		</div>
		<div class="text">
		Enter the race you want to register for and your email address.
		</div>
	</div>
	<div class="num">
		<div class="count">
		2
		</div>
		<div class="text">
		We'll send you an email the day the registration opens.
		</div>
	</div>
	<div class="num nobar">
		<div class="count">
		3
		</div>
		<div class="text">
		You never miss a race registration again in your life.
		</div>
	</div>
</div>
<div class="question">
	<!-- <p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p> -->
	<% if @user and @user.errors.any? %>
	<div class="clearform">
		<div class="input error_explanation">
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
	<% end %>
	<%= render 'questions/search'%>
</div>

app/views/pages/privacy.html.erb
<div class="pages">Privacy Policy</div>

app/views/pages/terms.html.erb
<div class="pages">Terms</div>

app/views/pages/thank_you.html.erb
<div class="pages">Thank you, we will send you an email when we find out about the registration date for the <%= params[:betold] %> race. An email has been sent to <%= params[:email] %> to complete the registration.</div>

app/views/shared/_getsatisfaction.html.erb
<script type="text/javascript" charset="utf-8">
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript" charset="utf-8">
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";  
  feedback_widget_options.company = "utellmewhen";
  feedback_widget_options.placement = "left";
  feedback_widget_options.color = "#f28600";
  feedback_widget_options.style = "idea";

  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>

app/views/shared/_googleanalytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26986089-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_zendesk.html.erb
<script type="text/javascript" src="//asset0.zendesk.com/external/zenbox/v2.3/zenbox.js"></script>
<style type="text/css" media="screen, projection">
  @import url(//asset0.zendesk.com/external/zenbox/v2.3/zenbox.css);
</style>
<script type="text/javascript">
  if (typeof(Zenbox) !== "undefined") {
    Zenbox.init({
      dropboxID:   "20029022",
      url:         "https://tellmewhen.zendesk.com",
      tabID:       "feedback",
      tabColor:    "#FF9B30",
      tabPosition: "Left"
    });
  }
</script>